# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db7f595b9c22b8d622c62ea1c0c8546c3400fe2bb31e938f7b898a5528261dad25d901af30c23f6b8208e8cbb3d87928bf0f8aeb70005ed5686e143b967edac9

test:
  secret_key_base: 2025f59b3b063f096e9750e78d2d7051214ca87a3b03da08cea225c2aff13b58e2256e0775ca73d3ec0553f2a9fbcc8297a2f471bc267b4900d3a45249859993

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
